command_alias_start_index: 200
keybindings:
  prefix_table: Space
title:
  style: align=centre,bold
  prefix: tmux
  prefix_style: fg=#46a436,align=centre,bold
position:
  x: R
  y: P
custom_variables:
- name: log_info
  value: '#[fg=#46a436,italics] [info]#[default]#[italics]'
macros:
- name: reload-config
  commands:
  - display "#{log_info} Loading config... "
  - source-file $HOME/.tmux.conf
  - display -p "\n\n... Press ENTER to continue"
- name: restart-pane
  commands:
  - display "#{log_info} Restarting pane"
  - 'respawnp -k -c #{pane_current_path}'
items:
- name: Run command (prefix+:)
  key: space
  command: command-prompt
- name: Last window (prefix+l)
  key: tab
  command: last-window
- name: Last pane (prefix+;)
  key: '`'
  command: last-pane
- separator: true
- name: +Windows
  key: w
  menu:
  - name: Last (prefix+l)
    key: tab
    command: last-window
  - name: Choose (prefix+w)
    key: w
    command: choose-tree -Zw
  - name: Previous (prefix+p)
    key: p
    command: previous-window
  - name: Next (prefix+n)
    key: n
    command: next-window
  - name: New (prefix+c)
    key: c
    command: 'neww -c #{pane_current_path}'
  - separator: true
  - name: +Layout
    key: l
    menu:
    - name: Next
      key: l
      command: nextl
      transient: true
    - name: Tiled
      key: t
      command: selectl tiled
    - name: Horizontal
      key: h
      command: selectl even-horizontal
    - name: Vertical
      key: v
      command: selectl even-vertical
    - name: Horizontal main
      key: H
      command: selectl main-horizontal
    - name: Vertical main
      key: V
      command: selectl main-vertical
  - name: Split horizontal (prefix+|)
    key: '|'
    command: 'splitw -h -c #{pane_current_path}'
  - name: Split vertical (prefix+-)
    key: '-'
    command: 'splitw -v -c #{pane_current_path}'
  - name: Rotate
    key: o
    command: rotatew
    transient: true
  - name: Rotate reverse
    key: O
    command: rotatew -D
    transient: true
  - separator: true
  - name: Rename (prefix+,)
    key: R
    command: command-prompt -I "#W" "renamew -- \"%%\""
  - name: Kill (prefix+&)
    key: X
    command: 'confirm -p "Kill window #W? (y/n)" killw'
- name: +Panes
  key: p
  menu:
  - name: Last (prefix+;)
    key: tab
    command: lastp
  - name: Choose (prefix+q)
    key: p
    command: displayp -d 0
  - separator: true
  - name: Left (prefix+←)
    key: h
    command: selectp -L
  - name: Down (prefix+↓)
    key: j
    command: selectp -D
  - name: Up (prefix+↑)
    key: k
    command: selectp -U
  - name: Right (prefix+→)
    key: l
    command: selectp -R
  - separator: true
  - name: Zoom (prefix+z)
    key: z
    command: resizep -Z
  - name: +Resize
    key: r
    menu:
    - name: Left
      key: h
      command: resizep -L
      transient: true
    - name: Down
      key: j
      command: resizep -D
      transient: true
    - name: Up
      key: k
      command: resizep -U
      transient: true
    - name: Right
      key: l
      command: resizep -R
      transient: true
    - name: Left more
      key: H
      command: resizep -L 10
      transient: true
    - name: Down more
      key: J
      command: resizep -D 10
      transient: true
    - name: Up more
      key: K
      command: resizep -U 10
      transient: true
    - name: Right more
      key: L
      command: resizep -R 10
      transient: true
  - name: Swap left
    key: H
    command: swapp -t "{left-of}"
  - name: Swap down
    key: J
    command: swapp -t "{down-of}"
  - name: Swap up
    key: K
    command: swapp -t "{up-of}"
  - name: Swap right
    key: L
    command: swapp -t "{right-of}"
  - name: Break
    key: '!'
    command: break-pane
  - separator: true
  - name: Mark
    key: m
    command: selectp -m
  - name: Unmark
    key: M
    command: selectp -M
  - name: Capture
    key: C
    command: capture-pane
  - name: Respawn pane
    key: R
    macro: restart-pane
  - name: Kill (prefix+x)
    key: X
    command: 'confirm -p "Kill pane #P? (y/n)" killp'
- name: +Buffers
  key: b
  menu:
  - name: Choose
    key: b
    command: choose-buffer -Z
  - name: List
    key: l
    command: lsb
  - name: Paste (prefix+])
    key: p
    command: pasteb
- name: +Sessions
  key: s
  menu:
  - name: Choose (prefix+s)
    key: s
    command: choose-tree -Zs
  - name: New
    key: C
    command: new-session
  - name: Switch last (prefix+L)
    key: g
    command: switch-client -l
  - separator: true
  - name: Rename (prefix+$)
    key: r
    command: command-prompt -I "#S" "rename-session -- \"%%\""
  - name: Resurrect restore (prefix+C-r)
    key: R
    command: run-shell ~/.tmux/plugins/tmux-resurrect/scripts/restore.sh
  - name: Resurrect save (prefix+C-s)
    key: S
    command: run-shell ~/.tmux/plugins/tmux-resurrect/scripts/save.sh
- name: +Tools
  key: t
  menu:
  - name: FZF menu (prefix+F)
    key: f
    command: run-shell ~/.tmux/plugins/tmux-fzf/main.sh
  - name: Fingers (prefix+H)
    key: F
    command: run-shell ~/.tmux/plugins/tmux-fingers/tmux-fingers.sh
  - name: Copy mode (prefix+[)
    key: c
    command: copy-mode
- name: +Client
  key: C
  menu:
  - name: Choose (prefix+D)
    key: c
    command: choose-client -Z
  - name: Last
    key: l
    command: switchc -l
  - name: Previous
    key: p
    command: switchc -p
  - name: Next
    key: n
    command: switchc -n
  - separator: true
  - name: Refresh
    key: R
    command: refresh
  - name: +Plugins
    key: P
    menu:
    - name: Install (prefix+I)
      key: i
      command: run-shell $TMUX_PLUGIN_MANAGER_PATH/tpm/bindings/install_plugins
    - name: Update (prefix+U)
      key: u
      command: run-shell $TMUX_PLUGIN_MANAGER_PATH/tpm/bindings/update_plugins
    - name: Clean (prefix+alt+u)
      key: c
      command: run-shell $TMUX_PLUGIN_MANAGER_PATH/tpm/bindings/clean_plugins
  - name: Detach (prefix+d)
    key: D
    command: detach
  - name: Suspend
    key: Z
    command: suspendc
  - separator: true
  - name: Reload config (prefix+r)
    key: r
    macro: reload-config
  - name: Customize
    key: ','
    command: customize-mode -Z
- separator: true
- name: Time (prefix+t)
  key: T
  command: clock-mode
- name: Show messages (prefix+~)
  key: '~'
  command: show-messages
- name: +Keys (prefix+?)
  key: '?'
  command: list-keys -N
