# Package declarations for declarative installation
# This file defines packages that should be installed on different platforms

[packages.brews]
packages = [
    "git",
    "unzip",
    "nushell",
    "nvim",
    "starship",
    "zoxide",
    "fzf",
    "zellij",
    "tmux",
    "lazydocker",
    "carapace",
    "zk",
    "atuin",
    "direnv",
    "fd",
    "ripgrep",
    "tealdeer",
    "television",
    "ugrep",
    "uutils-coreutils",
    "yq",
    "bitwarden-cli",
    "gemini-cli",
    "git-delta",
    "glow",
    "mob",
    "just",
    "mise",
    "podlet",
]

[packages.casks]
packages = ["lm-studio"]

[packages.flatpaks]
packages = ["com.bitwarden.desktop", "it.mijorus.gearlever"]


[packages.linux]
packages = ["unzip", "curl", "wget"]

[packages.npm]
packages = ["@devcontainers/cli"]
